# Generated by Django 5.0.7 on 2024-08-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0002_board_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="summary",
            field=models.TextField(null=True),
        ),
    ]
